### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by yuguitao** [heguixiang/Android-VINS#1]
Error:A problem occurred configuring project ':app'.
> executing external native build for cmake E:\yuguitao\CameraAR\Source\Android-VINS-master\Android-VINS-master\app\CMakeLists.txt

Seems no related code in below directory: 
https://github.com/heguixiang/Android-VINS/tree/master/app/src/main/cpp/src

Miss to checkin?

**Comment by heguixiang** [comment]
You can git pull again now, the .git directory exist in the path of /app/src/main/cpp/src lead to the section code wasn't pushed on Github. Thank you for your reminder.

**Comment by yuguitao** [comment]
one more link error:

Error:error: '../../../../src/main/jniLibs/armeabi-v7a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it

**Comment by heguixiang** [comment]
Put your ThirdParty lib to /app/src/main/jniLibs/arch/，including opencv， ceres，boost library.

**Comment by yuguitao** [comment]
**two more issues:
1. MH01.txt should be added to app\src\main\cpp\data\timestamps
2. Still assert failed:**

_`09-30 10:11:36.097 30368-30368/? E/Zygote: v2
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD checking this for 10211
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD not a persona
09-30 10:11:36.098 30368-30368/? E/Zygote: accessInfo : 0
09-30 10:11:36.098 30368-30368/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0007, [-1 -1 -1 -1 0 1]
09-30 10:11:36.099 30368-30368/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.hezhaoxin.solomon.vins_android 
09-30 10:11:36.101 30368-30368/? I/art: Late-enabling -Xcheck:jni
09-30 10:11:36.122 30368-30368/com.hezhaoxin.solomon.vins_android D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
09-30 10:11:36.145 30368-30368/com.hezhaoxin.solomon.vins_android I/ResourcesManager: updateResourcesForOpenThemeChange for Desktop mode 
09-30 10:11:36.173 30368-30368/com.hezhaoxin.solomon.vins_android V/ActivityThread: performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc [en_US] ldltr sw360dp w360dp h668dp 480dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.151}
09-30 10:11:36.176 30368-30368/com.hezhaoxin.solomon.vins_android W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: OpenCL is not availble
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: don't use OpenCL
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Failed creating the context...
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the matrix m: 3.000000, -1.000000, 2.500000, 1.500000 
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the vector v: 4.000000, 3.000000
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74 
                                                                            
                                                                            DenseQRSolver::Solve
                                                                                                               Delta   Cumulative
                                                                                                       Setup :    0.00001      0.00001
                                                                                                       Solve :    0.00006      0.00007
                                                                                                    TearDown :    0.00003      0.00011
                                                                                                       Total :    0.00001      0.00011
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74 
                                                                            
                                                                            DenseQRSolver::Solve
                                                                                                               Delta   Cumulative
                                                                                                       Setup :    0.00001      0.00001
                                                                                                       Solve :    0.00001      0.00002
                                                                                                    TearDown :    0.00001      0.00002
                                                                                                       Total :    0.00000      0.00002
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74 
                                                                            
                                                                            DenseQRSolver::Solve
                                                                                                               Delta   Cumulative
                                                                                                       Setup :    0.00001      0.00001
                                                                                                       Solve :    0.00001      0.00001
                                                                                                    TearDown :    0.00001      0.00002
                                                                                                       Total :    0.00000      0.00002
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android D/native: trust_region_minimizer.cc:683 Terminating: Parameter tolerance reached. Relative step_norm: 1.666426e-09 <= 1.000000e-08.
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: X: 5.000000 -> 10.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: A: 123
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: B: 123.120000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: filesystem test pass
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: TEST LOG
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/vins_parameter: ACC_N:0.000000 , ACC_W:0.000000 ,GYR_N:0.000000 , GYR_W:0.000000 , G.z():0.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android E/cv::error(): OpenCV Error: Assertion failed (!fixedSize()) in void cv::_OutputArray::release() const, file /Volumes/Linux/builds/master_pack-android/opencv/modules/core/src/matrix.cpp, line 2570
09-30 10:11:36.436 30368-30368/com.hezhaoxin.solomon.vins_android A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30368 (on.vins_android)
                                                                          
                                                                          [ 09-30 10:11:36.437  3130: 3130 W/         ]
                                                                          debuggerd: handling request: pid=30368 uid=10211 gid=10211 tid=30368
`_

**Comment by heguixiang** [comment]
please read README.MD carefully, the assertion failure means your app have no permission or data path error



发自我的小米手机
在 俞贵涛 <notifications@github.com>，2017年9月30日 上午10:23写道：

**two more issues:

  1.  MH01.txt should be added to app\src\main\cpp\data\timestamps
  2.  Still assert failed:**

_`09-30 10:11:36.097 30368-30368/? E/Zygote: v2
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD checking this for 10211
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD not a persona
09-30 10:11:36.098 30368-30368/? E/Zygote: accessInfo : 0
09-30 10:11:36.098 30368-30368/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2], Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0007, [-1 -1 -1 -1 0 1]
09-30 10:11:36.099 30368-30368/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.hezhaoxin.solomon.vins_android
09-30 10:11:36.101 30368-30368/? I/art: Late-enabling -Xcheck:jni
09-30 10:11:36.122 30368-30368/com.hezhaoxin.solomon.vins_android D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
09-30 10:11:36.145 30368-30368/com.hezhaoxin.solomon.vins_android I/ResourcesManager: updateResourcesForOpenThemeChange for Desktop mode
09-30 10:11:36.173 30368-30368/com.hezhaoxin.solomon.vins_android V/ActivityThread: performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc [en_US] ldltr sw360dp w360dp h668dp 480dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.151}
09-30 10:11:36.176 30368-30368/com.hezhaoxin.solomon.vins_android W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: OpenCL is not availble
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: don't use OpenCL
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Failed creating the context...
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the matrix m: 3.000000, -1.000000, 2.500000, 1.500000
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the vector v: 4.000000, 3.000000
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00006      0.00007
                                                                                                TearDown :    0.00003      0.00011
                                                                                                   Total :    0.00001      0.00011


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00001      0.00002
                                                                                                TearDown :    0.00001      0.00002
                                                                                                   Total :    0.00000      0.00002


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00001      0.00001
                                                                                                TearDown :    0.00001      0.00002
                                                                                                   Total :    0.00000      0.00002


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android D/native: trust_region_minimizer.cc:683 Terminating: Parameter tolerance reached. Relative step_norm: 1.666426e-09 <= 1.000000e-08.
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: X: 5.000000 -> 10.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: A: 123
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: B: 123.120000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: filesystem test pass
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: TEST LOG
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/vins_parameter: ACC_N:0.000000 , ACC_W:0.000000 ,GYR_N:0.000000 , GYR_W:0.000000 , G.z():0.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android E/cv::error(): OpenCV Error: Assertion failed (!fixedSize()) in void cv::_OutputArray::release() const, file /Volumes/Linux/builds/master_pack-android/opencv/modules/core/src/matrix.cpp, line 2570
09-30 10:11:36.436 30368-30368/com.hezhaoxin.solomon.vins_android A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30368 (on.vins_android)

                                                                      [ 09-30 10:11:36.437  3130: 3130 W/         ]
                                                                      debuggerd: handling request: pid=30368 uid=10211 gid=10211 tid=30368


`_

**Comment by heguixiang** [comment]
make sure your app can access data which you put in the memory,including permission and right data path



发自我的小米手机
在 俞贵涛 <notifications@github.com>，2017年9月30日 上午10:23写道：

**two more issues:

  1.  MH01.txt should be added to app\src\main\cpp\data\timestamps
  2.  Still assert failed:**

_`09-30 10:11:36.097 30368-30368/? E/Zygote: v2
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD checking this for 10211
09-30 10:11:36.097 30368-30368/? I/libpersona: KNOX_SDCARD not a persona
09-30 10:11:36.098 30368-30368/? E/Zygote: accessInfo : 0
09-30 10:11:36.098 30368-30368/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2], Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0007, [-1 -1 -1 -1 0 1]
09-30 10:11:36.099 30368-30368/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.hezhaoxin.solomon.vins_android
09-30 10:11:36.101 30368-30368/? I/art: Late-enabling -Xcheck:jni
09-30 10:11:36.122 30368-30368/com.hezhaoxin.solomon.vins_android D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
09-30 10:11:36.145 30368-30368/com.hezhaoxin.solomon.vins_android I/ResourcesManager: updateResourcesForOpenThemeChange for Desktop mode
09-30 10:11:36.173 30368-30368/com.hezhaoxin.solomon.vins_android V/ActivityThread: performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 ?mcc?mnc [en_US] ldltr sw360dp w360dp h668dp 480dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.151}
09-30 10:11:36.176 30368-30368/com.hezhaoxin.solomon.vins_android W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: OpenCL is not availble
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: don't use OpenCL
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Failed creating the context...
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the matrix m: 3.000000, -1.000000, 2.500000, 1.500000
09-30 10:11:36.433 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: Here is the vector v: 4.000000, 3.000000
09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00006      0.00007
                                                                                                TearDown :    0.00003      0.00011
                                                                                                   Total :    0.00001      0.00011


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00001      0.00002
                                                                                                TearDown :    0.00001      0.00002
                                                                                                   Total :    0.00000      0.00002


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android V/native: wall_time.cc:74

                                                                        DenseQRSolver::Solve
                                                                                                           Delta   Cumulative
                                                                                                   Setup :    0.00001      0.00001
                                                                                                   Solve :    0.00001      0.00001
                                                                                                TearDown :    0.00001      0.00002
                                                                                                   Total :    0.00000      0.00002


09-30 10:11:36.434 30368-30368/com.hezhaoxin.solomon.vins_android D/native: trust_region_minimizer.cc:683 Terminating: Parameter tolerance reached. Relative step_norm: 1.666426e-09 <= 1.000000e-08.
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: X: 5.000000 -> 10.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: A: 123
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: B: 123.120000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: filesystem test pass
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/openclTest: TEST LOG
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android D/vins_parameter: ACC_N:0.000000 , ACC_W:0.000000 ,GYR_N:0.000000 , GYR_W:0.000000 , G.z():0.000000
09-30 10:11:36.435 30368-30368/com.hezhaoxin.solomon.vins_android E/cv::error(): OpenCV Error: Assertion failed (!fixedSize()) in void cv::_OutputArray::release() const, file /Volumes/Linux/builds/master_pack-android/opencv/modules/core/src/matrix.cpp, line 2570
09-30 10:11:36.436 30368-30368/com.hezhaoxin.solomon.vins_android A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30368 (on.vins_android)

                                                                      [ 09-30 10:11:36.437  3130: 3130 W/         ]
                                                                      debuggerd: handling request: pid=30368 uid=10211 gid=10211 tid=30368


`_

**Comment by yuguitao** [comment]
“APP PERMISSIONS” 's "Storage" is enabled, then it is ok.
