### ISSUE TITLE
Gradle sync failed: Cause: java.net.URISyntaxException

### ISSUE THREAD

**Issue by sc25world** [heguixiang/Android-VINS#7]
`Cause: java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\workspace\code\slam\VINS-Android\app\src\main\jniLibs
Illegal character in opaque part at index 2: D:\workspace\code\slam\VINS-Android\app\src\main\jniLibs`

**Comment by yt-oh96** [comment]
Hi, I got the same error, but could you tell me what you did if you did it?
